### ISSUE TITLE
임시 파일과 결과물을 구분하여 저장하고, 의미있는 파일들만 아카이브하는것이 어떨까요?

### ISSUE THREAD

**Issue by lovit** [sophia-jihye/bis_speeches_text_dataset#3]
이 레포지토리 내 코드들의 목적은 두 가지라고 인식됩니다.

1) pdf 형식의 파일을 스크래핑하여 저장한다.
2) pdf 형식의 파일을 txt 형식으로 변환하여 저장한다.

그렇다면 그 이외의 파일들은 사실 불필요하다고 판단됩니다. 특히 분기별로 pickle 파일을 만든다고 하였는데, 웹스크래핑 도중의 네트워크 문제가 일어난다면, 가장 마지막까지 스크래핑된 파일을 탐색한 뒤, 그때까지의 파일들은 스크래핑 하지 않고 뒤의 파일들을 스크래핑 하도록 continue 기능을 구현하면 되는 문제라 생각됩니다.

또한 작업 도중 발생하는 로그와 같은 정보는 의미가 있지만, 임시로 이용하는 파일은 작업이 완료된 뒤 제거하는 것이 좋지 않을까요?

**Comment by sophia-jihye** [comment]
가장 최근에 스크랩핑된 파일을 탐색하여 뒤의 파일들을 스크랩핑하고, 프로세스가 끝나면 임시로 이용하는 .pkl 파일들은 삭제하도록 코드를 수정하였습니다. 

언급하신 방법으로 구현하니 훨씬 사용하기 편리한 형태가 된 것 같습니다. 의견 감사합니다!

**Comment by lovit** [comment]
해결된듯하니 이슈는 직접 닫겠습니다.
