### ISSUE TITLE
최종결과물의 형식에 대하여 README 에 설명이 필요합니다.

### ISSUE THREAD

**Issue by lovit** [sophia-jihye/bis_speeches_text_dataset#4]
현재의 [README](https://github.com/sophia-jihye/bis_speeches_text_dataset/blob/f1574b8c7c4150847458d381cfe97cd8272b36ef/README.md) 에는 두 가지 파일이 최종 결과물이라 적혀있습니다.

`output/bis_w_content_FINAL.csv`, `output/bis_w_content_FINAL.pkl` 이 두 파일 내의 정보가 무엇인지 어떤 형식인지 열어서 살펴보기 전에 README 나 `output` 디렉토리의 README 에 기록이 되어 있어야 좋다고 생각됩니다.

또한 이 두 종류의 파일은 같은 정보를 포함하는 파일인가요? 그렇다면 왜 중복하여 두 개의 파일로 만든건가요?

+ `output` 디렉토리 이름에 대해서는 #1 에 추가 커멘트 남겼습니다.

**Comment by sophia-jihye** [comment]
앗, 커밋 내용에 이슈넘버를 언급하면 이슈가 closed 되는 군요! 
해당 내용을 반영하여 README를 수정하고 output/bis_w_content_FINAL.pkl 파일은 저장하지 않도록 코드를 수정하였습니다. 

output/bis_w_content_FINAL.pkl 파일과 .csv 파일을 각각 만들었던 이유는 제가 개인적으로 두  파일을 다 사용하기 위해서였는데요 (.csv 파일은 직접 파일을 열어 title 또는 content의 내용을 눈으로 살펴보고 엑셀 필터 기능을 이용하여 간단하게 단어 빈도 수를 조회해보고자 하는 목적으로 사용하였고, .pkl 파일은 Python을 이용하여 데이터를 탐색할 때 간단하게 load하여 사용할 목적으로 사용하였습니다.) , 동일한 내용을 담고있으니 .pkl파일은 삭제하는 것이 맞는 것 같습니다. 의견 감사합니다.

**Comment by lovit** [comment]
관리자는 closed issues 를 re open 할 수 있습니다. 하단에 reopen issues 버튼이 보일겁니다.
